ayanamsa: raman # as supported by the underlying package, pyswisseph.
year: 2020
month: 1
day: 4
hour: 6
minute: 0
second: 0
# Timezone is split into hour and minute parts. The hour part could be negative.
utcHour: 5
utcMinute: 30
# Latitude and Longitude in Decimal Degrees (as given by Google Maps).
latitude: 23.101
longitude: 77.461
frequency: "60min" # as supported by pandas.date_range.frequency.
periods: 100
query: "dharma > 75"
exportTo: "./.sample.csv"
customColumns:
  dharma: "h1 + h5 + h9"
  muhurtaYogaEffect: "positive + negative"
  maxOfDharma:
    max: ["h1", "h5", "h9"]
skipColumns:
  - yogas
order:
  dharma: descending
  muhurtaYogaEffect: descending
